### ISSUE TITLE
Function to convert metadata to json

### ISSUE THREAD

**Issue by kuriwaki** [gdcc/pyDataverse#116]
### Question/ Feature Request

May have missed this, but is there a helper function to create the metadata json files of a dataset (e.g. [this one](https://github.com/gdcc/pyDataverse/blob/master/tests/data/user-guide/dataset.json) in your examples) from more common input like a CSV or a python dictionary?

I am basically wondering if the user  needs to write out JSON manually to upload the metadata to a dataset/datafile, which seems tedious.

**Comment by skasberger** [comment]
- The import can be done with help of the CSV templates.
- The export is done by the `json()` function.

You can check this out in our user guide tutorials:

- https://pydataverse.readthedocs.io/en/latest/user/basic-usage.html#create-dataset
- https://pydataverse.readthedocs.io/en/latest/user/advanced-usage.html
- https://pydataverse.readthedocs.io/en/latest/user/csv-templates.html
