### ISSUE TITLE
Include guestbook option in full dataset upload?

### ISSUE THREAD

**Issue by rdhlily** [gdcc/pyDataverse#141]
Before moving on, please check some things first:

* [X] Your issue may already be reported! Please search on the [issue tracker](https://github.com/gdcc/pyDataverse/issues) before creating one.
* [X] Use our issue templates for bug reports and feature requests, if that's what you need.
* [X] Are you running the expected version of pyDataverse? (check via `pip freeze`).
* [X] Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. For more information, see the [Contributor Guide](https://pydataverse.readthedocs.io/en/master/contributing/contributing.html).
* [X] We as maintainers foster an open and welcoming environment. Be respectfull, supportive and nice to each other! :)

### Issue

Hello, I am working on creating datasets in bulk and would like my template guestbook to be attached to each. I have not found a way to include a guestbook in the template JSONs or in the code. Is this an available feature? If not, is there another way to apply a guestbook to every dataset in a collection so that I do not need to do so manually?

Any insights are appreciated! Thanks so much.

**Comment by pdurbin** [comment]
@rdhlily hi! Guestbooks are an area of Dataverse that are mostly managed through the GUI. In fact, I believe the only thing you can do via API with guestbooks is download them: https://guides.dataverse.org/en/5.9/api/native-api.html#retrieve-guestbook-responses-for-a-dataverse-collection

If you'd like the ability, for example, to set a dataset's guestbook via API, please open an issue upstream at https://github.com/IQSS/dataverse/issues

We tend to work in small chunks, so issues with smaller scope are better. Please create as many as you need. Thanks.

**Comment by skasberger** [comment]
This issue is not part of pyDataverse.
