### ISSUE TITLE
pyDataverse conda package

### ISSUE THREAD

**Issue by PennyHow** [gdcc/pyDataverse#159]
I would like to request pyDataverse to be made available as a conda package, as well as the already available pip package. This is mainly because we use pyDataverse in our packages and would like to distribute these as conda packages, however, this requires all dependencies to have conda distributions.

I have managed to make a conda-forge version of the most recent pyDataverse verison `0.3.1` using `grayskull`, which generates a build script from the pypi package (this is similar to [these instructions](https://docs.conda.io/projects/conda-build/en/latest/user-guide/tutorials/build-pkgs-skeleton.html) on how to make conda builds from pypi packages).

```
$ grayskull pypi --strict-conda-forge pydataverse
```

The conda package can then be built from the generated `meta.yaml` file.

```
$ conda-build pydataverse
```

I tested this local build (linux-64, on Python 3.8) and it seems to be working fine (make sure that the local environment for the build is included in conda channels).

```
$ conda install --use-local pydataverse
$ conda list
```

And finally the package can be uploaded to Anaconda like so.

```
$ anaconda upload pydataverse-0.3.1-py_0.tar.bz2
```

I know you would probably want versions for different platforms and Python iterations. I'm happy to help with continuing this if needed. If this is something that you do not want to pursue then I'm also happy to make pydataverse as a conda package and distribute it myself... but I feel it is better if it comes from you guys!

**Comment by pdurbin** [comment]
@JR-1991 @skasberger what do you think?!?

Should we take up @PennyHow on her generous offer to make pyDataverse into a Conda package and distribute it herself?!?

@PennyHow if you go ahead with this, would we be able to switch the package to coming from Dataverse (or the GDCC) in the future?

@PennyHow are aware that there is also EasyDataverse at https://pypi.org/project/easyDataverse/ ? @JR-1991 is the author.

**Comment by PennyHow** [comment]
> @PennyHow if you go ahead with this, would we be able to switch the package to coming from Dataverse (or the GDCC) in the future?

You can through the `anaconda upload` method I outlined previously. I have not checked through the approach from @izahn but I am think it should be possible. 

I'm happy to start this process through this approach through conda-forge. The main things I need to know are:
- What platforms do you want it distributed on? Windows, Linux, macOS, or all three?
- What Python versions do you want it distributed on? For our package, we would like 3.8, 3.9 and 3.10 so any extras just let me know

> @PennyHow are aware that there is also EasyDataverse at https://pypi.org/project/easyDataverse/ ? @JR-1991 is the author.

No, I had not seen this before! Thanks for pointing it out - this may be a lightweight option that we could use in the future instead of `pyDataverse`. Would you prefer us to use this and focus our efforts on getting a conda distribution for EasyDataverse?

**Comment by izahn** [comment]
> > @PennyHow if you go ahead with this, would we be able to switch the package to coming from Dataverse (or the GDCC) in the future?
> 
> You can through the `anaconda upload` method I outlined previously. I have not checked through the approach from @izahn but I am think it should be possible.

I'm not sure what "coming from Dataverse" means, nor am I familiar with GDCC. In terms of conda packages, yes you can create and distribute packages through your own conda channel, but I don't recommend this. Joining forces and distributing your package in the conda-forge channel is recommended because it makes it easy to keep your package compatible with the rest of the vast array of packages already distributed through the conda-forge channel.

**Comment by izahn** [comment]
> * What platforms do you want it distributed on? Windows, Linux, macOS, or all three?
> * What Python versions do you want it distributed on? For our package, we would like 3.8, 3.9 and 3.10 so any extras just let me know

This package probably can/should be `noarch` as documented in https://conda-forge.org/docs/maintainer/knowledge_base.html#noarch-python . This will simplify maintenance since it only has to be built once and doesn't need separate versions for each OS or Python version.

**Comment by PennyHow** [comment]
I have been playing around with it and think I have a staged recipe of pyDataverse ready to open a PR to https://github.com/conda-forge/staged-recipes. Of course, I will wait until you have come to an agreement @pdurbin @skasberger @JR-1991. It should be easy enough to do this with easyDataverse instead/in addition if you wish.

The main thing is the [meta.yaml](https://github.com/PennyHow/staged-recipes/blob/pydataverse/recipes/pydataverse/meta.yaml). Feel free to take a look and edit if needed. The GDCC organisation is listed as a maintainer (although I need to check that organisations can be linked) along with myself and @izahn.

**Comment by pdurbin** [comment]
@PennyHow thanks! I don't know Conda but maybe @izahn can take a look at that yml file. It seems reasonable to me (but yeah, I dunno if orgs can be maintainers).

@JR-1991 any thoughts on having EasyDataverse in Conda?

**Comment by JR-1991** [comment]
@pdurbin that would definitely also make sense for EasyDataverse. I would add it once the new version is out 🙂

**Comment by PennyHow** [comment]
Thanks @izahn. I'll edit the `meta.yaml` file and take out gdcc as a maintainer. @pdurbin, would you like to be listed as a maintainer instead? Just so that there is some representation from the organisation in the maintainers list?

**Comment by pdurbin** [comment]
@PennyHow oh sure, you can throw me on there. I'll try not to break anything. 😅 Thanks!

**Comment by pdurbin** [comment]
Nice! Yes, I see it here: https://anaconda.org/conda-forge/pydataverse

@PennyHow sure! Yes, it would be nice to point out in the pyDataverse docs that the package is now available on Conda! Thanks!

**Comment by PennyHow** [comment]
PR is here https://github.com/gdcc/pyDataverse/pull/160
