### ISSUE TITLE
Get DOI for pyDataverse

### ISSUE THREAD

**Issue by skasberger** [gdcc/pyDataverse#25]
Get a DOI for the repo. Check, how versioning of releases is done. when is a new doi assigned to the repo/code?

* https://guides.github.com/activities/citable-code/
* add it to ORCID
* add DOI Badge in README and Docs (`![doi:10.7910/DVN/TJCLKP](https://img.shields.io/badge/DOI-10.7910%2FDVN%2FTJCLKP-orange.svg)](https://doi.org/10.7910/DVN/TJCLKP)`)

**Comment by pdurbin** [comment]
https://guides.github.com/activities/citable-code/ leads you to Zenodo but you could deposit your code into Dataverse and get a DOI from Dataverse. You could deposit it into https://dataverse.harvard.edu for example.

You can also put a DOI "badge" in your README on the GitHub side the looks something like this:

<img width="427" alt="Screen Shot 2019-07-01 at 2 51 39 PM" src="https://user-images.githubusercontent.com/21006/60459694-d5632d80-9c0f-11e9-8a81-740599d0c3c4.png">

Here's how I added the badge above:

https://github.com/IQSS/open-source-at-harvard/commit/a701b308c9ada78998e12471dd087bc0129eec90

**Comment by poikilotherm** [comment]
Maybe this is sth. for [GDCC/dvcli](https://github.com/GlobalDataverseCommunityConsortium/dvcli)?

I am about to ramp up development for this tool for CI usage of deploying research software to Dataverse. This would be a great case of dogfooding your own library :smile:

**Comment by skasberger** [comment]
Again, great. :)

My strategy so far is to create one for each major release. Maybe thats not best, cause I dont know, when the v1.0 will be ever released. and the minor releases so far have quite big changes in it. 

So, @poikilotherm, what do you think? One for each minor version change, or stick to the principle of only major releases? Maybe another way could be to make the next release the 1.0 one. am a bit hesitant, cause on other libraries I watch, they are too. And its still a huge way to go to be really production ready, tested, mature code (e.g. API module testing).

**Comment by skasberger** [comment]
will create one DOI for the 0.x.x versions to begin with.

**Comment by skasberger** [comment]
Done.

https://zenodo.org/record/4470151
https://doi.org/10.5281/zenodo.4470151
