### ISSUE TITLE
Release follow-ups

### ISSUE THREAD

**Issue by skasberger** [gdcc/pyDataverse#69]
**@skasberger**

* [x] Presentations
  * [x] AUSSDA team
  * [x] Dataverse Community call
* [x] Share release
  * [x] Dataverse Community Mailinglist
  * [x] Twitter
  * [x] GDCC Slack
* [x] Write release notes template: features, improvements, thanks, use-cases (optional)
* [x] close Milestone

**Doc review by @djbrooke**

* [x] #81

**Comment by skasberger** [comment]
@pdurbin Would it be possible, that someone from IQSS does a lectorate of the documentation? Would be great, if a native speaker looks over it once, so it does not sound completely awefull. Must not be perfect, but at least good enough so it can be called english. :)

**Comment by djbrooke** [comment]
thx @pdurbin for the mention.

@skasberger I should be able to help you with a documentation review for this release. We can also see if anyone in the community is willing to help with future versions. 

What is the timeline for this? When do you need it done? Also, what's the process for updating the documentation?

**Comment by djbrooke** [comment]
(nevermind my last questions, I see https://github.com/gdcc/pyDataverse/tree/master/src/pyDataverse/docs/source mentioned in the contributor guide. I'll review and make a PR.)

**Comment by skasberger** [comment]
Thanks @djbrooke, that's great work. Will review the PR later. 

Regarding future reviews: In general, this release was a big doc-update. So this review was more effort than most others ever will be. by far. But in general, it would be great to have a few persons to contact for docs related issues. Any ideas welcome, how we can approach the community for this.
