### ISSUE TITLE
Correct get_user() call

### ISSUE THREAD

**Issue by raprasad** [gdcc/pyDataverse#77]
Error: e.g. Builds path with `/users/:me` instead of `/api/v1/users/:me` 

- Use `self.base_url_api_native` instead of `self.base_url`
- Line should be:
    ```
     url = f"{self.base_url_api_native}/users/:me" 
     ```

https://github.com/gdcc/pyDataverse/blob/77ea8af515ea837e55c6c0a747a31dc23cf7cba9/src/pyDataverse/api.py#L2189

**Comment by ecowan** [comment]
API call is updated here: https://github.com/opendp/pyDataverse/commit/4edaac3d6d2cc253bd62614d750018e52983068d #

**Comment by skasberger** [comment]
@ecowan Would you please make a PR with this against develop.

**Comment by ecowan** [comment]
@skasberger I don't have permissions to push to the repo, but my changes are represented in our fork (the link above). Thanks!

**Comment by skasberger** [comment]
done. https://github.com/gdcc/pyDataverse/pull/114
